version: "3.3"
services:
 
  nginx:
    image: nginx:1.15-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nextcloud
    volumes:
      - /data/dotfiles/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /data/dotfiles/nginx/cert/:/etc/nginx/cert/
  
  nextcloud:
    image: ownyourbits/nextcloudpi
    restart: always
    command: "192.168.1.100"
    ports:
      - "4443:4443"
      - "8443:443"
    networks:
      - nextcloud
    environment:
      TZ: 'Europe/Madrid'
      VIRTUAL_HOST: 'nextcloud.caliope.duckdns.org'
    volumes:
      - "/data/docker/nextcloudplus/:/data"
      - "/data/smb_data/:/data/smb_data/"

  samba:
    image: dperson/samba:armhf
    networks:
      - default
    environment:
      TZ: 'Europe/Madrid'
      USERID: '1000'
      GROUPID: '1000'
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /data/smb_data/:/share
    command: '-p -s "share;/share;yes;no;no;pi" -u "pi;rt040818"'

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80/tcp"
      - "443/tcp"
    networks:
      - nextcloud
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'RT040818.'
    # Volumes store your data between container upgrades
    volumes:
      - '/data/docker/pihole/etc/pihole/:/etc/pihole/'
      - '/data/docker/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.0.0.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  plex:
    image: jaymoulin/plex:1.16.5
    expose:
      - 32400
      - 33400
    hostname: caliope
    volumes:
      - /data/docker/plex/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - /data/smb_data/General_smb/torrent/Videos:/media
      - /data/docker/plex/tmp:/tmp
    restart: unless-stopped
    network_mode: "host"

networks:
  nextcloud:
  default:
  lan:
    external:
      name: lan

